/**
 * Samomes
 *
 * Copyright (C) 2025 Mikhail Lapshin
 *
 * This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0
 * International License. To view a copy of this license, visit
 * http://creativecommons.org/licenses/by-nc-sa/4.0/ or send a letter to
 * Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 *
 * You are free to:
 *  - Share — copy and redistribute the material in any medium or format
 *  - Adapt — remix, transform, and build upon the material
 *
 * Under the following terms:
 *  - Attribution — You must give appropriate credit
 *  - NonCommercial — You may not use the material for commercial purposes
 *  - ShareAlike — If you remix, transform, or build upon the material,
 *    you must distribute your contributions under the same license as the original
 *
 * No warranties are given. The license may not give you all of the permissions
 * necessary for your intended use.
 */

export const FERTILIZERS: FertilizerType[] = [
  {
    key: 'apt3Complete',
    name: 'APT 3 / Complete',
    isLiquid: true,
    isPercent: true,
    ions: {
      N: 0.7,
      P2O5: 0.9,
      K2O: 7,
      Fe: 0.09,
      Mn: 0.015,
      MgO: 1.6,
      Cu: 0.0004,
      B: 0.015,
      Zn: 0.007,
      Mo: 0.000001,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-18',
  },
  // Prestige
  {
    key: 'prestigeFitoMinMacro',
    name: 'Prestige FitoMin Macro',
    isLiquid: true,
    isPercent: false,
    ions: {
      N: 10.7,
      K: 32.0,
      P: 1.5,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-04',
  },
  {
    key: 'prestigeFitoMinKaliy',
    name: 'Prestige FitoMin Калий',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 50,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-04',
  },
  {
    key: 'prestigeFitoMinMicro',
    name: 'Prestige FitoMin Micro',
    isLiquid: true,
    isPercent: true,
    ions: {
      K: 1.2,
      Fe: 0.15,
      Mg: 0.08,
      B: 0.006,
      Mn: 0.05,
      Mo: 0.003,
      Zn: 0.002,
      Cu: 0.002,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-04',
  },
  {
    key: 'prestigeFitoMinZhelezo',
    name: 'Prestige FitoMin Железо',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 6,
      Mn: 1.1,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-04',
  },
  // Aquabalance
  {
    key: 'aquabalancePolnyKompleksTotal',
    name: 'Aquabalance полный комплекс Total',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 4.65,
      PO4: 0.45,
      K: 1.45,
      Ca: 0.14,
      Mg: 0.17,
      Fe: 0.07,
      Mn: 0.015,
      B: 0.008,
      Zn: 0.006,
      Cu: 0.0015,
      Mo: 0.002,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceFerroBalans',
    name: 'Aquabalance Ферро Баланс',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 0.7,
      Mn: 0.1,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceKaliyBalans',
    name: 'Aquabalance Калий Баланс',
    isLiquid: true,
    isPercent: true,
    ions: {
      K: 5,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceNitroBalans',
    name: 'Aquabalance Нитро Баланс',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 4.65,
      K: 1.45,
      Ca: 0.14,
      Mg: 0.17,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceFosfoBalans',
    name: 'Aquabalance Фосфо Баланс',
    isLiquid: true,
    isPercent: true,
    ions: {
      PO4: 0.45,
      K: 0.095,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceMakroBalans',
    name: 'Aquabalance Макро Баланс',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 4.65,
      PO4: 0.45,
      K: 1.45,
      Ca: 0.14,
      Mg: 0.17,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceMikroBalans',
    name: 'Aquabalance Микро Баланс',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 0.2,
      Mn: 0.05,
      Zn: 0.01,
      B: 0.009,
      Cu: 0.003,
      Mo: 0.003,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceMikroBalansPlusK',
    name: 'Aquabalance Микро Баланс + K',
    isLiquid: true,
    isPercent: true,
    ions: {
      K: 3,
      Fe: 0.2,
      Mn: 0.05,
      Zn: 0.01,
      B: 0.009,
      Cu: 0.003,
      Mo: 0.003,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceTotalMokh',
    name: 'Aquabalance Тотал-Мох',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 5,
      PO4: 0.5,
      Fe: 0.05,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки. Содержит макроэлементы: '
      + 'азот, фосфор, калий, кальций, магний, а так же микроэле- менты: железо, марганец,'
      + 'бор в том числе в органической форме.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalancePremiumMicroKHLess4',
    name: 'Aquabalance Premium Micro (KH<4)',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 0.2,
      Mn: 0.08,
      B: 0.008,
      Zn: 0.005,
      Cu: 0.01,
      Mo: 0.006,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalancePremiumMicroKHGreater4',
    name: 'Aquabalance Premium Micro (KH>4)',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 0.32,
      Mn: 0.08,
      B: 0.009,
      Zn: 0.008,
      Cu: 0.008,
      Mo: 0.003,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalancePremiumMakroKorrektorPK',
    name: 'Aquabalance Premium Макро корректор P+K',
    isLiquid: true,
    isPercent: true,
    ions: {
      PO4: 0.9,
      K2O: 0.4,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalancePremiumMakroKorrektorNK',
    name: 'Aquabalance Premium Макро корректор N+K',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 10,
      K: 1.76,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
  },
  {
    key: 'aquabalancePremiumMakroKompleksNPK',
    name: 'Aquabalance Premium Макро комплекс NPK',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 9.6,
      PO4: 0.9,
      K: 2,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalancePremiumFeMn',
    name: 'Aquabalance Premium Fe+Mn',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 1.0,
      Mn: 0.2,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceKolorBalans',
    name: 'Aquabalance Колор Баланс',
    isLiquid: true,
    isPercent: true,
    ions: {
      Mg: 3,
      Fe: 0.1,
      Mn: 0.05,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquabalanceGHBuster',
    name: 'Aquabalance GH-бустер',
    isLiquid: false,
    isPercent: true,
    ions: {
      Ca: 17.2,
      Mg: 4.3,
    },
    hardness: {
      gh: 3.5,
      kh: 0,
      amount: 14,
      volume: 100,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  {
    key: 'aquabalanceAquaBuster',
    name: 'Aquabalance Aqua-бустер',
    isPercent: true,
    isLiquid: false,
    ions: {
      Ca: 15,
      Mg: 4.3,
    },
    hardness: {
      gh: 4.5,
      kh: 2.25,
      amount: 7,
      volume: 50,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  {
    key: 'aquabalanceGhKaltsiy',
    name: 'Aquabalance Gh-кальций',
    isLiquid: true,
    isPercent: false,
    ions: {
      Ca: 75,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  {
    key: 'aquabalanceGhMagniy',
    name: 'Aquabalance Gh-магний',
    isLiquid: true,
    isPercent: false,
    ions: {
      Mg: 75,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  // Aquayer
  {
    key: 'aquayerMakroPlus',
    name: 'Aquayer Макро+',
    isLiquid: true,
    isPercent: false,
    ions: {
      N: 8.21,
      P: 1.20,
      K: 20.43,
    },
    description: 'Это фирменное удобрение. Данные взяты на сайте производителя https://aquayer.com',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquayerMikroPlus',
    name: 'Aquayer Микро+',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 6.930,
      Fe: 1.2,
      Mg: 0.8,
      Mn: 0.4,
      B: 0.072,
      Mo: 0.03,
      Cu: 0.045,
      Zn: 0.015,
      Co: 0.007,
    },
    description: 'Это фирменное удобрение. Данные взяты на сайте производителя https://aquayer.com',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquayerZhelezoPlus',
    name: 'Aquayer Железо+',
    isLiquid: true,
    isPercent: false,
    ions: {
      Fe: 7.00,
      Mg: 1.3,
    },
    description: 'Это фирменное удобрение. Данные взяты на сайте производителя https://aquayer.com',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquayerKaliyPlus',
    name: 'Aquayer Калий+',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 50,
    },
    description: 'Это фирменное удобрение. Данные взяты на сайте производителя https://aquayer.com',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquayerSmartMakroNitrat',
    name: 'Aquayer Смарт Макро (Нитрат)',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 72,
      K: 45.3,
    },
    description: 'Это фирменное удобрение. Данные взяты на сайте производителя https://aquayer.com',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquayerSmartMakroFosfat',
    name: 'Aquayer Смарт Макро (Фосфат)',
    isLiquid: true,
    isPercent: false,
    ions: {
      PO4: 7.2,
      K: 3,
    },
    description: 'Это фирменное удобрение. Данные взяты на сайте производителя https://aquayer.com',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquayerRemineralGHKHPlus',
    name: 'Aquayer Remineral GH/KH+',
    isLiquid: false,
    isPercent: true,
    ions: {
      Ca: 17.7,
      Mg: 5.5,
    },
    hardness: {
      gh: 3,
      kh: 2,
      amount: 4,
      volume: 50,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  // Aquaerus
  {
    key: 'aquaerusMakro',
    name: 'Aquaerus Макро',
    isLiquid: true,
    isPercent: false,
    ions: {
      N: 9.428,
      P: 1.394,
      K: 23.354,
    },
    description: 'Это фирменное удобрение. Данные взяты c этикетки.',
    updatedAt: '2025-05-02',
  },
  {
    key: 'aquaerusMikro',
    name: 'Aquaerus Микро',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 7.920,
      Fe: 1.372,
      Mg: 0.915,
      Mn: 0.457,
      B: 0.082,
      Cu: 0.052,
      Mo: 0.035,
      Zn: 0.017,
      Co: 0.008,
    },
    description: 'Это фирменное удобрение. Данные взяты c этикетки.',
    updatedAt: '2025-05-02',
  },
  {
    key: 'aquaerusZhelezo',
    name: 'Aquaerus Железо',
    isLiquid: true,
    isPercent: false,
    ions: {
      Fe: 7.00,
      Mg: 1.3,
    },
    description: 'Это фирменное удобрение. Данные взяты c этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquaerusKaliy',
    name: 'Aquaerus Калий',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 50,
    },
    description: 'Это фирменное удобрение. Данные взяты c этикетки.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquaerusNitratPlus',
    name: 'Aquaerus Нитрат+',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 72,
      K: 45.3,
    },
    description: 'Это фирменное удобрение. ВНИМАНИЕ! Производитель не указал содержание калия в этом удобрении. '
      + 'Но в оригинальном удобрении калий присутствует. Также пользователи указывают на повышение калия в аквариуме.'
      + 'Поэтому безопаснее для аквариума будет учитывать калий как в удобрении Aquayer.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'aquaerusFosfatPlus',
    name: 'Aquaerus Фосфат+',
    isLiquid: true,
    isPercent: false,
    ions: {
      PO4: 7.2,
      K: 3,
    },
    description: 'Это фирменное удобрение. ВНИМАНИЕ! Производитель не указал содержание калия в этом удобрении. '
      + 'Но в оригинальном удобрении калий присутствует. Также пользователи указывают на повышение калия в аквариуме.'
      + 'Поэтому безопаснее для аквариума будет учитывать калий как в удобрении Aquayer.',
    updatedAt: '2025-03-03',
  },
  {
    key: 'seachemNitrogen',
    name: 'Seachem Nitrogen',
    isLiquid: true,
    isPercent: true,
    ions: {
      N: 1.5,
      K2O: 2,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта https://seachem.com/planted.php',
    updatedAt: '2025-03-04',
  },
  {
    key: 'seachemPhosphorus',
    name: 'Seachem Phosphorus',
    isLiquid: true,
    isPercent: true,
    ions: {
      P2O5: 0.3,
      K2O: 0.2,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта https://seachem.com/planted.php',
    updatedAt: '2025-03-04',
  },
  {
    key: 'seachemPotassium',
    name: 'Seachem Potassium',
    isLiquid: true,
    isPercent: true,
    ions: {
      K2O: 5,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта https://seachem.com/planted.php',
    updatedAt: '2025-03-04',
  },
  {
    key: 'seachemFlourish',
    name: 'Seachem Flourish',
    isLiquid: true,
    isPercent: true,
    ions: {
      N: 0.07,
      P2O5: 0.01,
      K2O: 0.37,
      Ca: 0.14,
      Mg: 0.11,
      S: 0.2773,
      B: 0.009,
      Cl: 1.15,
      Co: 0.0004,
      Cu: 0.0001,
      Fe: 0.32,
      Mn: 0.0118,
      Mo: 0.0009,
      Na: 0.13,
      Zn: 0.0007,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта https://seachem.com/planted.php',
    updatedAt: '2025-03-04',
  },
  {
    key: 'seachemFlourishAdvance',
    name: 'Seachem Flourish Advance',
    isLiquid: true,
    isPercent: true,
    ions: {
      P2O5: 0.04,
      K2O: 0.45,
      Ca: 0.04,
      Mg: 0.04,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта https://seachem.com/planted.php',
    updatedAt: '2025-03-04',
  },
  {
    key: 'seachemFlourishTrace',
    name: 'Seachem Flourish Trace',
    isLiquid: true,
    isPercent: true,
    ions: {
      B: 0.0028,
      Co: 0.00003,
      Cu: 0.0032,
      Mn: 0.0085,
      Mo: 0.0003,
      Zn: 0.0169,
      Rb: 0.000008,
      Ni: 0.000003,
      V: 0.000002,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта https://seachem.com/planted.php',
    updatedAt: '2025-03-04',
  },
  {
    key: 'seachemFlourishIron',
    name: 'Seachem Flourish Iron',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 1,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта https://seachem.com/planted.php',
    updatedAt: '2025-03-04',
  },
  {
    key: 'seachemEquilibrium',
    name: 'Seachem Equilibrium',
    isPercent: true,
    isLiquid: false,
    ions: {
      K2O: 23,
      Ca: 8.06,
      Mg: 2.41,
      Fe: 0.11,
      Mn: 0.06,
    },
    hardness: {
      gh: 3,
      kh: 0,
      amount: 16,
      volume: 80,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  // Tropica
  {
    key: 'tropicaPremiumNutrition',
    name: 'Tropica Premium Nutrition',
    isLiquid: true,
    isPercent: true,
    ions: {
      K: 0.8,
      Mg: 0.4,
      S: 0.9,
      B: 0.004,
      Cu: 0.006,
      Fe: 0.07,
      Mn: 0.04,
      Mo: 0.002,
      Zn: 0.002,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта '
      + 'https://tropica.com/en/plant-care/liquid-fertilisers/premium-nutrition/',
    updatedAt: '2025-03-04',
  },
  {
    key: 'tropicaSpecialisedNutrition',
    name: 'Tropica Specialised Nutrition',
    isLiquid: true,
    isPercent: true,
    ions: {
      N: 1.3,
      P: 0.1,
      K: 1,
      Mg: 0.4,
      S: 0.9,
      B: 0.004,
      Cu: 0.006,
      Fe: 0.07,
      Mn: 0.04,
      Mo: 0.002,
      Zn: 0.002,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта '
      + 'https://tropica.com/en/plant-care/liquid-fertilisers/specialised-nutrition/',
    updatedAt: '2025-03-04',
  },
  {
    key: 'dennerlePlantCarePro',
    name: 'Dennerle Plant Care Pro',
    isLiquid: true,
    isPercent: true,
    ions: {
      K2O: 2.8,
      S: 1,
      MgO: 0.78,
      Fe: 0.14,
      Mn: 0.047,
      Na: 0.008,
      B: 0.0075,
      Zn: 0.0056,
      Co: 0.0005,
      Cu: 0.0019,
      Mo: 0.0019,
      Ni: 0.0001,
      V: 0.00004,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://dennerle.com/en/collections/plantcare',
    updatedAt: '2025-05-02',
  },
  {
    key: 'dennerlePlantCareNPK',
    name: 'Dennerle Plant Care NPK',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 50,
      PO4: 4,
      K: 25,
      Mg: 5,
      Na: 4.4,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://dennerle.com/en/collections/plantcare',
    updatedAt: '2025-05-02',
  },
  {
    key: 'dennerlePlantCareN',
    name: 'Dennerle Plant Care N',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 100,
      Na: 23,
      K: 20,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://dennerle.com/en/collections/plantcare',
    updatedAt: '2025-05-02',
  },
  {
    key: 'dennerlePlantCareP',
    name: 'Dennerle Plant Care P',
    isLiquid: true,
    isPercent: false,
    ions: {
      PO4: 12.5,
      K: 5,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://dennerle.com/en/collections/plantcare',
    updatedAt: '2025-05-02',
  },
  {
    key: 'dennerlePlantCareK',
    name: 'Dennerle Plan Care K',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 50,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://dennerle.com/en/collections/plantcare',
    updatedAt: '2025-05-02',
  },
  {
    key: 'dennerleElixirBasic',
    name: 'Dennerle Elixir Basic',
    isLiquid: true,
    isPercent: true,
    ions: {
      N: 0.02,
      K2O: 0.11,
      Mg: 0.02,
      S: 0.14,
      B: 0.0018,
      Cu: 0.0005,
      Co: 0.0001,
      Fe: 0.025,
      Mn: 0.01,
      Mo: 0.001,
      Zn: 0.0005,
      Ni: 0.00004,
      V: 0.0001,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://dennerle.com/en/collections/plantcare',
    updatedAt: '2025-02-24',
  },
  {
    key: 'dennerleNPKBooster',
    name: 'Dennerle NPK Booster',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 50,
      PO4: 2,
      K: 10,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2021-08-14',
  },
  {
    key: 'dennerleScapersGreen',
    name: 'Dennerle Scaper\'s Green',
    isLiquid: true,
    isPercent: true,
    ions: {
      K: 1.08,
      B: 0.0006,
      Co: 0.001,
      Cu: 0.002,
      Fe: 0.133,
      Mn: 0.052,
      Mo: 0.003,
      Zn: 0.003,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2021-08-14',
  },
  {
    key: 'dennerleOsmoseReMineral',
    name: 'Dennerle Osmose ReMineral+',
    isLiquid: false,
    isPercent: true,
    ions: {
      // Ca: 45.5,
      // Mg: 9.5,
    },
    hardness: {
      gh: 2,
      kh: 1.3,
      amount: 10,
      volume: 100,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  {
    key: 'akvapozitivNitrogenPlus',
    name: 'Аквапозитив Азот+',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 6,
      K: 2.2,
      Ca: 0.3,
      Mg: 0.1,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivPhosphatePlus',
    name: 'Аквапозитив Фосфор+',
    isLiquid: true,
    isPercent: true,
    ions: {
      PO4: 0.5,
      K: 0.5,
      Mg: 0.1,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivMacroPlus',
    name: 'Аквапозитив Макро+',
    isLiquid: true,
    isPercent: true,
    ions: {
      NO3: 6,
      K: 2.3,
      PO4: 0.5,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivMicroPlus',
    name: 'Аквапозитив Микро+',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 0.13,
      Mn: 0.042,
      B: 0.01,
      Co: 0.0005,
      Cu: 0.0025,
      Mo: 0.0015,
      Zn: 0.007,
      Ni: 0.0002,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivFePlus',
    name: 'Аквапозитив Железо+',
    isLiquid: true,
    isPercent: true,
    ions: {
      Fe: 0.2,
      Mn: 0.04,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivNitrogenPlusPowder',
    name: 'Аквапозитив Азот+ (порошок)',
    isLiquid: false,
    isPercent: true,
    ions: {
      NO3: 6,
      K: 2,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivPhosphatePlusPowder',
    name: 'Аквапозитив Фосфор+ (порошок)',
    isLiquid: false,
    isPercent: true,
    ions: {
      PO4: 0.5,
      K: 0.5,
      Mg: 0.1,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivPotassiumPlusPowder',
    name: 'Аквапозитив Калий+ (порошок)',
    isLiquid: false,
    isPercent: true,
    ions: {
      K: 5,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivMagnesiumPowder',
    name: 'Аквапозитив Магний (порошок)',
    isLiquid: false,
    isPercent: true,
    ions: {
      Mg: 0.3,
    },
    description: 'Это фирменное удобрение. Данные взяты https://vk.com/akvapozitiv',
    updatedAt: '2025-03-04',
  },
  {
    key: 'akvapozitivGhPlus',
    name: 'Аквапозитив GH+',
    isLiquid: false,
    isPercent: true,
    ions: {
      Ca: 14,
      Mg: 3.5,
    },
    hardness: {
      gh: 6,
      kh: 0,
      amount: 2,
      volume: 10,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  {
    key: 'akvapozitivGhKhPlus',
    name: 'Аквапозитив GH/KH+',
    isLiquid: false,
    isPercent: true,
    ions: {
      Ca: 13.8,
      Mg: 3.4,
    },
    hardness: {
      gh: 8,
      kh: 3,
      amount: 3,
      volume: 10,
    },
    description: 'Это заводское удобрение. Все данные взяты с этикетки.',
  },
  {
    key: 'waterSciMicroXLOsmosis',
    name: 'WaterSci Micro XL для осмоса',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 10.48,
      S: 6.56,
      Mg: 5.5,
      Fe: 2.00,
      Mn: 0.52,
      Na: 0.37,
      B: 0.09,
      Zn: 0.05,
      Mo: 0.04,
      Co: 0.01,
      Cu: 0.03,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciMicroHalfFeXLOsmosis',
    name: 'WaterSci Micro 1/2 Fe XL для осмоса',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 10.48,
      S: 6.56,
      Mg: 5.5,
      Fe: 1.00,
      Mn: 0.26,
      Na: 0.37,
      B: 0.09,
      Zn: 0.05,
      Mo: 0.04,
      Co: 0.01,
      Cu: 0.03,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciHalfFeGluconateXLOsmosis',
    name: 'WaterSci 1/2 Fe gluconate XL для осмоса',
    isLiquid: true,
    isPercent: false,
    ions: {
      Fe: 1.00,
      Mn: 0.26,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciNKXLAnyWater',
    name: 'WaterSci NK XL для любой воды',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 90.77,
      N: 22.93,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciPKXLAnyWater',
    name: 'WaterSci PK XL для любой воды',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 90.77,
      P: 2.82,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciKXLAnyWater',
    name: 'WaterSci K XL для любой воды',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 90.77,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciMicro3In1LTapWater',
    name: 'WaterSci Micro 3 in 1 L для водопроводной воды',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 3.41,
      S: 2.13,
      Mg: 1.79,
      Fe: 0.65,
      Mn: 0.17,
      Na: 0.12,
      B: 0.02,
      Zn: 0.02,
      Mo: 0.01,
      Co: 0.01,
      Cu: 0.01,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciMacroNPKLTapWater',
    name: 'WaterSci Mаcro NPK L для водопроводной воды',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 90.77,
      N: 10.71,
      P: 1.41,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
    updatedAt: '2025-02-24',
  },
  {
    key: 'waterSciRemineralGHPlus',
    name: 'WaterSci Remineral Gh+',
    isLiquid: true,
    isPercent: false,
    ions: {
      Ca: 27.54,
      Mg: 6.48,
    },
    hardness: {
      gh: 8,
      kh: 0,
      amount: 1,
      volume: 1,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
  },
  {
    key: 'waterSciRemineralKHPlus',
    name: 'WaterSci Remineral Kh+',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 7.65,
      Na: 26.23,
      SO4: 9.4,
      CO3: 68.4,
    },
    hardness: {
      gh: 0,
      kh: 4,
      amount: 1,
      volume: 1,
    },
    description: 'Это фирменное удобрение. Все данные взяты из официальных источников:\n'
      + 'https://watersci.ru\n'
      + 'https://vk.com/watersci',
  },
  {
    key: 'easyLifeNitro',
    name: 'Easy Life: Nitro',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 100,
      K: 65,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-21',
  },
  {
    key: 'easyLifeFosfo',
    name: 'Easy Life: Fosfo',
    isLiquid: true,
    isPercent: false,
    ions: {
      PO4: 10,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-21',
  },
  {
    key: 'easyLifePotassium',
    name: 'Easy Life: Potassium',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 40,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-21',
  },
  {
    key: 'easyLifeProFito',
    name: 'Easy Life: ProFito',
    isLiquid: true,
    isPercent: false,
    ions: {
      K: 4.80,
      Fe: 2.40,
      Mg: 0.90,
      Mn: 0.40,
      B: 0.08,
      Mo: 0.02,
      Zn: 0.02,
      Co: 0.01,
      Ni: 0.01,
      Cu: 0,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-21',
  },
  {
    key: 'easyLifeGreenScape',
    name: 'Easy Life: GreenScape',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 100,
      PO4: 10,
      K: 65,
      Fe: 2,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-21',
  },
  {
    key: 'easyLifeRedScape',
    name: 'Easy Life: RedScape',
    isLiquid: true,
    isPercent: false,
    ions: {
      NO3: 20,
      PO4: 10,
      K: 16.5,
      Fe: 2,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-21',
  },
  {
    key: 'easyLifeFerro',
    name: 'Easy Life: Ferro',
    isLiquid: true,
    isPercent: false,
    ions: {
      Fe: 10,
    },
    description: 'Это фирменное удобрение. Все данные взяты с этикетки.',
    updatedAt: '2025-02-21',
  },
  // Tetra
  {
    key: 'tetraPlantaMin',
    name: 'Tetra PlantaMin',
    isLiquid: true,
    isPercent: true,
    ions: {
      K2O: 1,
      Fe: 0.2,
      B: 0.005,
      Mn: 0.01,
      Zn: 0.002,
      S: 0.5,
      Na: 0.95,
    },
    description: 'Это фирменное удобрение. Данные взяты с сайта магазина https://www.aquasabi.com/Tetra-PlantaMin',
    updatedAt: '2025-03-04',
  },
];

export const FERTILIZER_NAMES_EN: {
  key: string;
  name: string;
  description: string;
}[] = [
  {
    key: 'apt3Complete',
    name: 'APT 3 / Complete',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'prestigeFitoMinMacro',
    name: 'Prestige FitoMin Macro',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'prestigeFitoMinKaliy',
    name: 'Prestige FitoMin Potassium',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'prestigeFitoMinMicro',
    name: 'Prestige FitoMin Micro',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'prestigeFitoMinZhelezo',
    name: 'Prestige FitoMin Iron',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalancePolnyKompleksTotal',
    name: 'Aquabalance Complete Complex Total',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceFerroBalans',
    name: 'Aquabalance Ferro Balance',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceKaliyBalans',
    name: 'Aquabalance Potassium Balance',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceNitroBalans',
    name: 'Aquabalance Nitro Balance',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceFosfoBalans',
    name: 'Aquabalance Phospho Balance',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceMakroBalans',
    name: 'Aquabalance Macro Balance',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceMikroBalans',
    name: 'Aquabalance Micro Balance',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceMikroBalansPlusK',
    name: 'Aquabalance Micro Balance + K',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceTotalMokh',
    name: 'Aquabalance Total-Moss',
    description: 'This is a branded fertilizer. All data taken from the label. Contains macroelements: '
      + 'nitrogen, phosphorus, potassium, calcium, magnesium, as well as microelements: iron, manganese, '
      + 'boron including in organic form.',
  },
  {
    key: 'aquabalancePremiumMicroKHLess4',
    name: 'Aquabalance Premium Micro (KH<4)',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalancePremiumMicroKHGreater4',
    name: 'Aquabalance Premium Micro (KH>4)',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalancePremiumMakroKorrektorPK',
    name: 'Aquabalance Premium Macro Corrector P+K',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalancePremiumMakroKorrektorNK',
    name: 'Aquabalance Premium Macro Corrector N+K',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalancePremiumMakroKompleksNPK',
    name: 'Aquabalance Premium Macro Complex NPK',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalancePremiumFeMn',
    name: 'Aquabalance Premium Fe+Mn',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceKolorBalans',
    name: 'Aquabalance Color Balance',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceGHBuster',
    name: 'Aquabalance GH-booster',
    description: 'This is a factory fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceAquaBuster',
    name: 'Aquabalance Aqua-booster',
    description: 'This is a factory fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceGhKaltsiy',
    name: 'Aquabalance GH-calcium',
    description: 'This is a factory fertilizer. All data taken from the label.',
  },
  {
    key: 'aquabalanceGhMagniy',
    name: 'Aquabalance GH-magnesium',
    description: 'This is a factory fertilizer. All data taken from the label.',
  },
  {
    key: 'aquayerMakroPlus',
    name: 'Aquayer Macro+',
    description: 'This is a branded fertilizer. Data taken from the manufacturer\'s website https://aquayer.com',
  },
  {
    key: 'aquayerMikroPlus',
    name: 'Aquayer Micro+',
    description: 'This is a branded fertilizer. Data taken from the manufacturer\'s website https://aquayer.com',
  },
  {
    key: 'aquayerZhelezoPlus',
    name: 'Aquayer Iron+',
    description: 'This is a branded fertilizer. Data taken from the manufacturer\'s website https://aquayer.com',
  },
  {
    key: 'aquayerKaliyPlus',
    name: 'Aquayer Potassium+',
    description: 'This is a branded fertilizer. Data taken from the manufacturer\'s website https://aquayer.com',
  },
  {
    key: 'aquayerSmartMakroNitrat',
    name: 'Aquayer Smart Macro (Nitrate)',
    description: 'This is a branded fertilizer. Data taken from the manufacturer\'s website https://aquayer.com',
  },
  {
    key: 'aquayerSmartMakroFosfat',
    name: 'Aquayer Smart Macro (Phosphate)',
    description: 'This is a branded fertilizer. Data taken from the manufacturer\'s website https://aquayer.com',
  },
  {
    key: 'aquayerRemineralGHKHPlus',
    name: 'Aquayer Remineral GH/KH+',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'aquaerusMakro',
    name: 'Aquaerus Macro',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'aquaerusMikro',
    name: 'Aquaerus Micro',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'aquaerusZhelezo',
    name: 'Aquaerus Iron',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'aquaerusKaliy',
    name: 'Aquaerus Potassium',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'aquaerusNitratPlus',
    name: 'Aquaerus Nitrate+',
    description: 'This is a branded fertilizer. WARNING! The manufacturer did not specify the potassium ' +
      'content in this fertilizer. But potassium is present in the original fertilizer. Users also ' +
      'indicate an increase in potassium in the aquarium. Therefore, it will be safer for the aquarium ' +
      'to consider potassium as in Aquayer fertilizer.',
  },
  {
    key: 'aquaerusFosfatPlus',
    name: 'Aquaerus Phosphate+',
    description: 'This is a branded fertilizer. WARNING! The manufacturer did not specify the potassium ' +
      'content in this fertilizer. But potassium is present in the original fertilizer. Users also indicate ' +
      'an increase in potassium in the aquarium. Therefore, it will be safer for the aquarium to consider ' +
      'potassium as in Aquayer fertilizer.',
  },
  {
    key: 'seachemNitrogen',
    name: 'Seachem Nitrogen',
    description: 'This is a branded fertilizer. Data taken from the website https://seachem.com/planted.php',
  },
  {
    key: 'seachemPhosphorus',
    name: 'Seachem Phosphorus',
    description: 'This is a branded fertilizer. Data taken from the website https://seachem.com/planted.php',
  },
  {
    key: 'seachemPotassium',
    name: 'Seachem Potassium',
    description: 'This is a branded fertilizer. Data taken from the website https://seachem.com/planted.php',
  },
  {
    key: 'seachemFlourish',
    name: 'Seachem Flourish',
    description: 'This is a branded fertilizer. Data taken from the website https://seachem.com/planted.php',
  },
  {
    key: 'seachemFlourishAdvance',
    name: 'Seachem Flourish Advance',
    description: 'This is a branded fertilizer. Data taken from the website https://seachem.com/planted.php',
  },
  {
    key: 'seachemFlourishTrace',
    name: 'Seachem Flourish Trace',
    description: 'This is a branded fertilizer. Data taken from the website https://seachem.com/planted.php',
  },
  {
    key: 'seachemFlourishIron',
    name: 'Seachem Flourish Iron',
    description: 'This is a branded fertilizer. Data taken from the website https://seachem.com/planted.php',
  },
  {
    key: 'seachemEquilibrium',
    name: 'Seachem Equilibrium',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'tropicaPremiumNutrition',
    name: 'Tropica Premium Nutrition',
    description: 'This is a branded fertilizer. Data taken from the website https://tropica.com/en/plant-care/liquid-fertilisers/premium-nutrition/',
  },
  {
    key: 'tropicaSpecialisedNutrition',
    name: 'Tropica Specialised Nutrition',
    description: 'This is a branded fertilizer. Data taken from the website https://tropica.com/en/plant-care/liquid-fertilisers/specialised-nutrition/',
  },
  {
    key: 'dennerlePlantCarePro',
    name: 'Dennerle Plant Care Pro',
    description: 'This is a branded fertilizer. All data taken from official sources: https://dennerle.com/en/collections/plantcare',
  },
  {
    key: 'dennerlePlantCareNPK',
    name: 'Dennerle Plant Care NPK',
    description: 'This is a branded fertilizer. All data taken from official sources: https://dennerle.com/en/collections/plantcare',
  },
  {
    key: 'dennerlePlantCareN',
    name: 'Dennerle Plant Care N',
    description: 'This is a branded fertilizer. All data taken from official sources: https://dennerle.com/en/collections/plantcare',
  },
  {
    key: 'dennerlePlantCareP',
    name: 'Dennerle Plant Care P',
    description: 'This is a branded fertilizer. All data taken from official sources: https://dennerle.com/en/collections/plantcare',
  },
  {
    key: 'dennerlePlanCareK',
    name: 'Dennerle Plant Care K',
    description: 'This is a branded fertilizer. All data taken from official sources: https://dennerle.com/en/collections/plantcare',
  },
  {
    key: 'dennerleElixirBasic',
    name: 'Dennerle Elixir Basic',
    description: 'This is a branded fertilizer. All data taken from official sources: https://dennerle.com/en/collections/plantcare',
  },
  {
    key: 'dennerleNPKBooster',
    name: 'Dennerle NPK Booster',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'dennerleScapersGreen',
    name: 'Dennerle Scaper\'s Green',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'dennerleOsmoseReMineral',
    name: 'Dennerle Osmose ReMineral+',
    description: 'This is a factory fertilizer. All data taken from the label.',
  },
  {
    key: 'akvapozitivNitrogenPlus',
    name: 'Akvapozitiv Nitrogen+',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivPhosphatePlus',
    name: 'Akvapozitiv Phosphorus+',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivMacroPlus',
    name: 'Akvapozitiv Macro+',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivMicroPlus',
    name: 'Akvapozitiv Micro+',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivFePlus',
    name: 'Akvapozitiv Iron+',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivNitrogenPlusPowder',
    name: 'Akvapozitiv Nitrogen+ (powder)',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivPhosphatePlusPowder',
    name: 'Akvapozitiv Phosphorus+ (powder)',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivPotassiumPlusPowder',
    name: 'Akvapozitiv Potassium+ (powder)',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivMagnesiumPowder',
    name: 'Akvapozitiv Magnesium (powder)',
    description: 'This is a branded fertilizer. Data taken from https://vk.com/akvapozitiv',
  },
  {
    key: 'akvapozitivGhPlus',
    name: 'Akvapozitiv GH+',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'akvapozitivGhKhPlus',
    name: 'Akvapozitiv GH/KH+',
    description: 'This is a branded fertilizer. Data taken from the label.',
  },
  {
    key: 'waterSciMicroXLOsmosis',
    name: 'WaterSci Micro XL for osmosis',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciMicroHalfFeXLOsmosis',
    name: 'WaterSci Micro 1/2 Fe XL for osmosis',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciHalfFeGluconateXLOsmosis',
    name: 'WaterSci 1/2 Fe gluconate XL for osmosis',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciNKXLAnyWater',
    name: 'WaterSci NK XL for any water',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciPKXLAnyWater',
    name: 'WaterSci PK XL for any water',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciKXLAnyWater',
    name: 'WaterSci K XL for any water',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciMicro3In1LTapWater',
    name: 'WaterSci Micro 3 in 1 L for tap water',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciMacroNPKLTapWater',
    name: 'WaterSci Macro NPK L for tap water',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciRemineralGHPlus',
    name: 'WaterSci Remineral GH+',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'waterSciRemineralKHPlus',
    name: 'WaterSci Remineral KH+',
    description: 'This is a branded fertilizer. All data taken from official sources: https://watersci.ru https://vk.com/watersci',
  },
  {
    key: 'easyLifeNitro',
    name: 'Easy Life: Nitro',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'easyLifeFosfo',
    name: 'Easy Life: Fosfo',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'easyLifePotassium',
    name: 'Easy Life: Potassium',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'easyLifeProFito',
    name: 'Easy Life: ProFito',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'easyLifeGreenScape',
    name: 'Easy Life: GreenScape',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'easyLifeRedScape',
    name: 'Easy Life: RedScape',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'easyLifeFerro',
    name: 'Easy Life: Ferro',
    description: 'This is a branded fertilizer. All data taken from the label.',
  },
  {
    key: 'tetraPlantaMin',
    name: 'Tetra PlantaMin',
    description: 'This is a branded fertilizer. Data taken from the store website https://www.aquasabi.com/Tetra-PlantaMin',
  },
];
